apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app
spec:
  selector:
    matchLabels:
      app: cicd-app
  replicas: 3
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cicd-app
    spec:
      containers:
      - name: cicd-app
        image:  public.ecr.aws/nginx/nginx:1.21
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          protocol: TCP
