apiVersion: v1
kind: Config

clusters:
- cluster:
    proxy-url: http://localhost:3000
    server: https://E686AEADB501E13FE32E9F83D18D4765.sk1.us-west-1.eks.amazonaws.com
  name: terraform-lab

users:
- name: adan
- name: bhagwat

contexts:
- context:
  name: terraform-lab
